/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v3/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LeasesGetter has a method to return a LeaseInterface.
// A group's client should implement this interface.
type LeasesGetter interface {
	Leases(namespace string) LeaseInterface
}

// LeaseInterface has methods to work with Lease resources.
type LeaseInterface interface {
	Create(ctx context.Context, lease *apiv1alpha1.Lease, opts v1.CreateOptions) (*apiv1alpha1.Lease, error)
	Update(ctx context.Context, lease *apiv1alpha1.Lease, opts v1.UpdateOptions) (*apiv1alpha1.Lease, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lease *apiv1alpha1.Lease, opts v1.UpdateOptions) (*apiv1alpha1.Lease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Lease, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.LeaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Lease, err error)
	Apply(ctx context.Context, lease *applyconfigurationapiv1alpha1.LeaseApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Lease, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, lease *applyconfigurationapiv1alpha1.LeaseApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Lease, err error)
	LeaseExpansion
}

// leases implements LeaseInterface
type leases struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.Lease, *apiv1alpha1.LeaseList, *applyconfigurationapiv1alpha1.LeaseApplyConfiguration]
}

// newLeases returns a Leases
func newLeases(c *OpenstackV1alpha1Client, namespace string) *leases {
	return &leases{
		gentype.NewClientWithListAndApply[*apiv1alpha1.Lease, *apiv1alpha1.LeaseList, *applyconfigurationapiv1alpha1.LeaseApplyConfiguration](
			"leases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Lease { return &apiv1alpha1.Lease{} },
			func() *apiv1alpha1.LeaseList { return &apiv1alpha1.LeaseList{} },
		),
	}
}
