/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../lease.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=lease.go -source=../lease.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock LeaseClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	leases "github.com/gophercloud/gophercloud/v2/openstack/reservation/v1/leases"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaseClient is a mock of LeaseClient interface.
type MockLeaseClient struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseClientMockRecorder
	isgomock struct{}
}

// MockLeaseClientMockRecorder is the mock recorder for MockLeaseClient.
type MockLeaseClientMockRecorder struct {
	mock *MockLeaseClient
}

// NewMockLeaseClient creates a new mock instance.
func NewMockLeaseClient(ctrl *gomock.Controller) *MockLeaseClient {
	mock := &MockLeaseClient{ctrl: ctrl}
	mock.recorder = &MockLeaseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaseClient) EXPECT() *MockLeaseClientMockRecorder {
	return m.recorder
}

// CreateLease mocks base method.
func (m *MockLeaseClient) CreateLease(ctx context.Context, opts leases.CreateOptsBuilder) (*leases.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLease", ctx, opts)
	ret0, _ := ret[0].(*leases.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLease indicates an expected call of CreateLease.
func (mr *MockLeaseClientMockRecorder) CreateLease(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLease", reflect.TypeOf((*MockLeaseClient)(nil).CreateLease), ctx, opts)
}

// DeleteLease mocks base method.
func (m *MockLeaseClient) DeleteLease(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLease", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLease indicates an expected call of DeleteLease.
func (mr *MockLeaseClientMockRecorder) DeleteLease(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLease", reflect.TypeOf((*MockLeaseClient)(nil).DeleteLease), ctx, resourceID)
}

// GetLease mocks base method.
func (m *MockLeaseClient) GetLease(ctx context.Context, resourceID string) (*leases.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLease", ctx, resourceID)
	ret0, _ := ret[0].(*leases.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLease indicates an expected call of GetLease.
func (mr *MockLeaseClientMockRecorder) GetLease(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLease", reflect.TypeOf((*MockLeaseClient)(nil).GetLease), ctx, resourceID)
}

// ListLeases mocks base method.
func (m *MockLeaseClient) ListLeases(ctx context.Context, listOpts leases.ListOptsBuilder) iter.Seq2[*leases.Lease, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLeases", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*leases.Lease, error])
	return ret0
}

// ListLeases indicates an expected call of ListLeases.
func (mr *MockLeaseClientMockRecorder) ListLeases(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLeases", reflect.TypeOf((*MockLeaseClient)(nil).ListLeases), ctx, listOpts)
}

// UpdateLease mocks base method.
func (m *MockLeaseClient) UpdateLease(ctx context.Context, id string, opts leases.UpdateOptsBuilder) (*leases.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLease", ctx, id, opts)
	ret0, _ := ret[0].(*leases.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLease indicates an expected call of UpdateLease.
func (mr *MockLeaseClientMockRecorder) UpdateLease(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLease", reflect.TypeOf((*MockLeaseClient)(nil).UpdateLease), ctx, id, opts)
}
