/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LeaseInstanceReservationApplyConfiguration represents a declarative configuration of the LeaseInstanceReservation type for use
// with apply.
type LeaseInstanceReservationApplyConfiguration struct {
	Amount             *int32  `json:"amount,omitempty"`
	Vcpus              *int32  `json:"vcpus,omitempty"`
	MemoryMB           *int32  `json:"memoryMB,omitempty"`
	DiskGB             *int32  `json:"diskGB,omitempty"`
	Affinity           *bool   `json:"affinity,omitempty"`
	ResourceProperties *string `json:"resourceProperties,omitempty"`
}

// LeaseInstanceReservationApplyConfiguration constructs a declarative configuration of the LeaseInstanceReservation type for use with
// apply.
func LeaseInstanceReservation() *LeaseInstanceReservationApplyConfiguration {
	return &LeaseInstanceReservationApplyConfiguration{}
}

// WithAmount sets the Amount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Amount field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithAmount(value int32) *LeaseInstanceReservationApplyConfiguration {
	b.Amount = &value
	return b
}

// WithVcpus sets the Vcpus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vcpus field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithVcpus(value int32) *LeaseInstanceReservationApplyConfiguration {
	b.Vcpus = &value
	return b
}

// WithMemoryMB sets the MemoryMB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryMB field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithMemoryMB(value int32) *LeaseInstanceReservationApplyConfiguration {
	b.MemoryMB = &value
	return b
}

// WithDiskGB sets the DiskGB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskGB field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithDiskGB(value int32) *LeaseInstanceReservationApplyConfiguration {
	b.DiskGB = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithAffinity(value bool) *LeaseInstanceReservationApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithResourceProperties sets the ResourceProperties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceProperties field is set to the value of the last call.
func (b *LeaseInstanceReservationApplyConfiguration) WithResourceProperties(value string) *LeaseInstanceReservationApplyConfiguration {
	b.ResourceProperties = &value
	return b
}
