/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LeaseReservationStatusApplyConfiguration represents a declarative configuration of the LeaseReservationStatus type for use
// with apply.
type LeaseReservationStatusApplyConfiguration struct {
	ID                   *string `json:"id,omitempty"`
	ResourceType         *string `json:"resourceType,omitempty"`
	Status               *string `json:"status,omitempty"`
	FlavorID             *string `json:"flavorID,omitempty"`
	ServerGroupID        *string `json:"serverGroupID,omitempty"`
	MissingResources     *bool   `json:"missingResources,omitempty"`
	ResourcesChanged     *bool   `json:"resourcesChanged,omitempty"`
	Min                  *int32  `json:"min,omitempty"`
	Max                  *int32  `json:"max,omitempty"`
	HypervisorProperties *string `json:"hypervisorProperties,omitempty"`
	ResourceProperties   *string `json:"resourceProperties,omitempty"`
	Amount               *int32  `json:"amount,omitempty"`
	Vcpus                *int32  `json:"vcpus,omitempty"`
	MemoryMB             *int32  `json:"memoryMB,omitempty"`
	DiskGB               *int32  `json:"diskGB,omitempty"`
	Affinity             *bool   `json:"affinity,omitempty"`
}

// LeaseReservationStatusApplyConfiguration constructs a declarative configuration of the LeaseReservationStatus type for use with
// apply.
func LeaseReservationStatus() *LeaseReservationStatusApplyConfiguration {
	return &LeaseReservationStatusApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithID(value string) *LeaseReservationStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithResourceType sets the ResourceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceType field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithResourceType(value string) *LeaseReservationStatusApplyConfiguration {
	b.ResourceType = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithStatus(value string) *LeaseReservationStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithFlavorID sets the FlavorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlavorID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithFlavorID(value string) *LeaseReservationStatusApplyConfiguration {
	b.FlavorID = &value
	return b
}

// WithServerGroupID sets the ServerGroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerGroupID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithServerGroupID(value string) *LeaseReservationStatusApplyConfiguration {
	b.ServerGroupID = &value
	return b
}

// WithMissingResources sets the MissingResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MissingResources field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithMissingResources(value bool) *LeaseReservationStatusApplyConfiguration {
	b.MissingResources = &value
	return b
}

// WithResourcesChanged sets the ResourcesChanged field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourcesChanged field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithResourcesChanged(value bool) *LeaseReservationStatusApplyConfiguration {
	b.ResourcesChanged = &value
	return b
}

// WithMin sets the Min field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Min field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithMin(value int32) *LeaseReservationStatusApplyConfiguration {
	b.Min = &value
	return b
}

// WithMax sets the Max field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Max field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithMax(value int32) *LeaseReservationStatusApplyConfiguration {
	b.Max = &value
	return b
}

// WithHypervisorProperties sets the HypervisorProperties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HypervisorProperties field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithHypervisorProperties(value string) *LeaseReservationStatusApplyConfiguration {
	b.HypervisorProperties = &value
	return b
}

// WithResourceProperties sets the ResourceProperties field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceProperties field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithResourceProperties(value string) *LeaseReservationStatusApplyConfiguration {
	b.ResourceProperties = &value
	return b
}

// WithAmount sets the Amount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Amount field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithAmount(value int32) *LeaseReservationStatusApplyConfiguration {
	b.Amount = &value
	return b
}

// WithVcpus sets the Vcpus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vcpus field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithVcpus(value int32) *LeaseReservationStatusApplyConfiguration {
	b.Vcpus = &value
	return b
}

// WithMemoryMB sets the MemoryMB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryMB field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithMemoryMB(value int32) *LeaseReservationStatusApplyConfiguration {
	b.MemoryMB = &value
	return b
}

// WithDiskGB sets the DiskGB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiskGB field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithDiskGB(value int32) *LeaseReservationStatusApplyConfiguration {
	b.DiskGB = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithAffinity(value bool) *LeaseReservationStatusApplyConfiguration {
	b.Affinity = &value
	return b
}
