/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LeaseResourceStatusApplyConfiguration represents a declarative configuration of the LeaseResourceStatus type for use
// with apply.
type LeaseResourceStatusApplyConfiguration struct {
	Name         *string                                    `json:"name,omitempty"`
	Status       *string                                    `json:"status,omitempty"`
	Degraded     *bool                                      `json:"degraded,omitempty"`
	StartDate    *v1.Time                                   `json:"startDate,omitempty"`
	EndDate      *v1.Time                                   `json:"endDate,omitempty"`
	ProjectID    *string                                    `json:"projectID,omitempty"`
	UserID       *string                                    `json:"userID,omitempty"`
	Reservations []LeaseReservationStatusApplyConfiguration `json:"reservations,omitempty"`
}

// LeaseResourceStatusApplyConfiguration constructs a declarative configuration of the LeaseResourceStatus type for use with
// apply.
func LeaseResourceStatus() *LeaseResourceStatusApplyConfiguration {
	return &LeaseResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithName(value string) *LeaseResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithStatus(value string) *LeaseResourceStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithDegraded sets the Degraded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Degraded field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithDegraded(value bool) *LeaseResourceStatusApplyConfiguration {
	b.Degraded = &value
	return b
}

// WithStartDate sets the StartDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartDate field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithStartDate(value v1.Time) *LeaseResourceStatusApplyConfiguration {
	b.StartDate = &value
	return b
}

// WithEndDate sets the EndDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndDate field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithEndDate(value v1.Time) *LeaseResourceStatusApplyConfiguration {
	b.EndDate = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithProjectID(value string) *LeaseResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithUserID sets the UserID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserID field is set to the value of the last call.
func (b *LeaseResourceStatusApplyConfiguration) WithUserID(value string) *LeaseResourceStatusApplyConfiguration {
	b.UserID = &value
	return b
}

// WithReservations adds the given value to the Reservations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Reservations field.
func (b *LeaseResourceStatusApplyConfiguration) WithReservations(values ...*LeaseReservationStatusApplyConfiguration) *LeaseResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReservations")
		}
		b.Reservations = append(b.Reservations, *values[i])
	}
	return b
}
