/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LeaseReservationStatusApplyConfiguration represents a declarative configuration of the LeaseReservationStatus type for use
// with apply.
type LeaseReservationStatusApplyConfiguration struct {
	ID            *string `json:"id,omitempty"`
	ResourceType  *string `json:"resourceType,omitempty"`
	Status        *string `json:"status,omitempty"`
	FlavorID      *string `json:"flavorID,omitempty"`
	ServerGroupID *string `json:"serverGroupID,omitempty"`
}

// LeaseReservationStatusApplyConfiguration constructs a declarative configuration of the LeaseReservationStatus type for use with
// apply.
func LeaseReservationStatus() *LeaseReservationStatusApplyConfiguration {
	return &LeaseReservationStatusApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithID(value string) *LeaseReservationStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithResourceType sets the ResourceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceType field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithResourceType(value string) *LeaseReservationStatusApplyConfiguration {
	b.ResourceType = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithStatus(value string) *LeaseReservationStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithFlavorID sets the FlavorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlavorID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithFlavorID(value string) *LeaseReservationStatusApplyConfiguration {
	b.FlavorID = &value
	return b
}

// WithServerGroupID sets the ServerGroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerGroupID field is set to the value of the last call.
func (b *LeaseReservationStatusApplyConfiguration) WithServerGroupID(value string) *LeaseReservationStatusApplyConfiguration {
	b.ServerGroupID = &value
	return b
}
